[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "brinc-dfr-2025-secret-xyz"

[auth.google]
client_id = "1056902385461-39k5hqdt6ni143qdi812qbglr50jufq0.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
